/* This file is generated by scripts/sync-apps.mjs. Do not edit by hand. */
import type { AppRegistryEntry } from "./apps";

export const generatedApps: AppRegistryEntry[] = [
  {
    "id": "breaklock-timer",
    "displayName": "Breaklock Timer",
    "displayNameKo": "Breaklock Timer",
    "taglineKo": "쉬는 시간에는 화면을 잠그는 포모도로 타이머",
    "platforms": [
      "macos"
    ],
    "minOS": "macOS 12.0+",
    "version": "1.8.1",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "macos",
        "url": "https://apps.apple.com/app/id6770569966",
        "label": "Mac App Store"
      }
    ],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy",
      "support": "https://homeninja.vercel.app/privacy"
    },
    "reporting": {
      "template": "breaklock-timer-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=breaklock-timer-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "callninja",
    "displayName": "CallNinja - Spam Call Blocker",
    "displayNameKo": "콜닌자 - 스팸 전화 패턴 차단",
    "taglineKo": "번호 범위를 직접 지정해서 차단",
    "platforms": [
      "ios"
    ],
    "minOS": "iOS 16.0+",
    "version": "1.0",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "ios",
        "url": "https://apps.apple.com/app/id6762523084",
        "label": "App Store"
      }
    ],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/callninja",
      "support": "https://homeninja.vercel.app/privacy/callninja"
    },
    "reporting": {
      "template": "callninja-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=callninja-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "centuryiris",
    "displayName": "Century Iris",
    "displayNameKo": "Century Iris",
    "taglineKo": "MacBook 조도센서로 외장 모니터 밝기와 색온도를 자동 조절합니다",
    "platforms": [
      "macos"
    ],
    "minOS": "macOS 15.0+, Apple Silicon",
    "version": "1.0",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "macos",
        "url": "https://apps.apple.com/app/id6763940089",
        "label": "Mac App Store"
      }
    ],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy",
      "support": "https://homeninja.vercel.app/privacy"
    },
    "reporting": {
      "template": "centuryiris-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=centuryiris-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "earth",
    "displayName": "Earth: World Time & Sky",
    "displayNameKo": "Earth: 세계 시간과 하늘",
    "taglineKo": "지구본 위에서 세계 시간을 읽는 앱",
    "platforms": [
      "ios"
    ],
    "minOS": "iOS 17.0+",
    "version": "1.0.0",
    "status": "unreleased",
    "updatedAt": "2026.08",
    "downloads": [],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/earth",
      "support": "https://homeninja.vercel.app/support/earth"
    },
    "reporting": {
      "template": "earth-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=earth-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "eatwater",
    "displayName": "The Bird That Drinks Water",
    "displayNameKo": "물을 마시는 새",
    "taglineKo": "물 마시는 시간을 알려주는 새",
    "platforms": [
      "ios"
    ],
    "minOS": "iOS 26.0+",
    "version": "1.0",
    "status": "unreleased",
    "updatedAt": "2026.08",
    "downloads": [],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/eatwater",
      "support": "https://homeninja.vercel.app/support/eatwater"
    },
    "reporting": {
      "template": "eatwater-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=eatwater-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "gnomon",
    "displayName": "Gnomon",
    "displayNameKo": "Gnomon",
    "taglineKo": "MacBook 조도센서로 외장 모니터 밝기를 자동으로 맞춰줍니다",
    "platforms": [
      "macos"
    ],
    "minOS": "macOS 15.0+, Apple Silicon",
    "version": "1.8.0",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "macos",
        "url": "https://github.com/sunpark20/gnomon/releases/tag/v1.8.0",
        "label": "macOS 다운로드"
      }
    ],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/gnomon",
      "support": "https://homeninja.vercel.app/support/gnomon"
    },
    "reporting": {
      "template": "gnomon-bug.yml",
      "locales": [
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=gnomon-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "memory-palace",
    "displayName": "기억의궁전 뇌모닉",
    "displayNameKo": "기억의궁전 뇌모닉",
    "taglineKo": "장소기억법을 배우는 뇌모닉 앱",
    "platforms": [
      "ios",
      "android"
    ],
    "minOS": "iOS 17.0+, Android 7.0+",
    "version": "1.0",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "ios",
        "url": "https://apps.apple.com/app/id6758509388",
        "label": "App Store"
      },
      {
        "platform": "android",
        "url": "https://play.google.com/store/apps/details?id=hungry.ex_frag",
        "label": "Google Play"
      }
    ],
    "web": {
      "privacy": "https://unruly-basil-c5e.notion.site/30b8253479f680079c88f13dd03c1172",
      "support": "https://sunpark20.github.io/"
    },
    "reporting": {
      "template": "memory-palace-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=memory-palace-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "quick-quit",
    "displayName": "Quick Quit",
    "displayNameKo": "Quick Quit",
    "taglineKo": "메뉴 막대에서 앱을 클릭 한 번으로 계속 종료하는 앱",
    "platforms": [
      "macos"
    ],
    "minOS": "macOS 13.0+",
    "version": "2.0.0",
    "status": "unreleased",
    "updatedAt": "2026.08",
    "downloads": [],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/quickquit",
      "support": "https://homeninja.vercel.app/support/quickquit"
    },
    "reporting": {
      "template": "quick-quit-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=quick-quit-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "snapcart",
    "displayName": "SnapCart Grocery Calculator",
    "displayNameKo": "찰칵 장값 계산기",
    "taglineKo": "가격표만 찍으면 장바구니 자동 합산",
    "platforms": [
      "ios"
    ],
    "minOS": "iOS 18.0+",
    "version": "2.01",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "ios",
        "url": "https://apps.apple.com/app/id6763238313",
        "label": "App Store"
      }
    ],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy",
      "support": "https://homeninja.vercel.app/privacy"
    },
    "reporting": {
      "template": "snapcart-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=snapcart-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "spamcall070",
    "displayName": "SpamCall070",
    "displayNameKo": "070 스팸 전화 차단",
    "taglineKo": "최초 1회 설정으로 벨소리도 울리지 않게 차단",
    "platforms": [
      "ios"
    ],
    "minOS": "iOS 16.0+",
    "version": "1.3",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "ios",
        "url": "https://apps.apple.com/app/id6762326707",
        "label": "App Store"
      }
    ],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/spamcall070",
      "support": "https://homeninja.vercel.app/privacy/spamcall070"
    },
    "reporting": {
      "template": "spamcall070-bug.yml",
      "locales": [
        "ko"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=spamcall070-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "yt-bulk-downloader",
    "displayName": "YT Chita",
    "displayNameKo": "YT Chita",
    "taglineKo": "YouTube 채널·재생목록·개별 영상을 저장하는 데스크톱 앱",
    "platforms": [
      "macos",
      "windows"
    ],
    "minOS": "macOS 10.15+, Windows 10·11 64-bit",
    "version": "1.5.3",
    "status": "released",
    "updatedAt": "2026.08",
    "downloads": [
      {
        "platform": "macos",
        "url": "https://github.com/sunpark20/YT-Chita/releases/latest",
        "label": "macOS 다운로드"
      },
      {
        "platform": "windows",
        "url": "https://github.com/sunpark20/YT-Chita/releases/latest",
        "label": "Windows 다운로드"
      },
      {
        "platform": "web",
        "url": "https://sunpark20.github.io/YT-Chita/",
        "label": "제품 소개 및 정책"
      }
    ],
    "web": {
      "privacy": "https://sunpark20.github.io/YT-Chita/#privacy",
      "support": "https://sunpark20.github.io/YT-Chita/#contact"
    },
    "reporting": {
      "template": "yt-bulk-downloader-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=yt-bulk-downloader-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  },
  {
    "id": "ytdi",
    "displayName": "ytdi",
    "displayNameKo": "ytdi",
    "taglineKo": "불안정한 회선에서도 이어받는 iPhone 영상 보관 앱",
    "platforms": [
      "ios"
    ],
    "minOS": "iOS 26.0+",
    "version": "0.1.0",
    "status": "unreleased",
    "updatedAt": "2026.08",
    "downloads": [],
    "web": {
      "privacy": "https://homeninja.vercel.app/privacy/ytdi",
      "support": "https://homeninja.vercel.app/support/ytdi"
    },
    "reporting": {
      "template": "ytdi-bug.yml",
      "locales": [
        "ko",
        "en"
      ],
      "url": "https://github.com/sunpark20/errorreport/issues/new?template=ytdi-bug.yml&version=unknown&build=unknown&os=unknown&device=unknown&diagnostics=unknown"
    }
  }
];
